hallucinations_messages:
  - Ку
  - Привет
  - Дарова
  - Как дела?
  - Стой
  - Слушай
  - Погоди
  - Стой тут
  - Завтра.
  - Пон
  - Понял
  - ээээээээээ
  - Поплачь чел
  - Пошёл нахуй
  - АААААА УЙДИ ОТСЮДА ГНИДА
  - Пиздец нахуй, опять спалили
  - Ну какого хуя ты сюда пришёл
  - Какого хрена ты сюда пришёл
  - Как ты сюда попал
  - Стоять
  - Не двигайся
  - Что ты тут делаешь?
  - Купи себе видеокарту нормальную
  - Админы дауны
  - Сервер параша
  - У них (админов) своя экономика
  - Блин Артёмка такой херовый админ
  - Унилион про
  - Лис про
  - Фергуст про
  - Заходит как то мужик в магазин шляп, надевает шляпу, она ему...
  - Купи себе видеокарту нормальную
  - Ты же в Морио живёшь?
  - Морио худший город
  - Морио лучший город
  - Как же заебала эта болезнь, да?
  - Мормо
  - Подпрул
  - /sex
  - /hack